'use client'

import { useEffect, useState } from 'react';
import styles from './page.module.css';
import { Gender, Player } from './player';
import PlayerInput from './PlayerInput';

interface MatchGeneratorModule {
    generateMatches: (
        players: Player[][],
        courts: number,
        games: number
    ) => string;
}

export default function AutoPage() {
    const [players, setPlayers] = useState<Player[][]>([[{ name: '', level: 1, gender: Gender.MALE }]]);
    const [courts, setCourts] = useState(2);
    const [games, setGames] = useState(4);

    const [wasmModule, setWasmModule] = useState<MatchGeneratorModule | null>(null);
    // State to track loading status
    const [isLoadingWasm, setIsLoadingWasm] = useState(true);
    // State to store results from Wasm
    const [generationResult, setGenerationResult] = useState<string | null>(null);
    // State for potential errors
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const loadWasm = async () => {
            try {
                setIsLoadingWasm(true);
                setError(null);
                // Dynamically import the JS glue code generated by Emscripten
                // The path is relative to the 'public' directory root
                const moduleFactory = (await import('../../../public/wasm/match_generator.js')).default;

                // Emscripten ES6 modules export a default function that resolves
                // with the module instance containing your exported functions.
                const instance = await moduleFactory();
                setWasmModule(instance as MatchGeneratorModule); // Assume the instance matches our interface
                console.log("Wasm module loaded successfully.");

            } catch (err) {
                console.error("Error loading Wasm module:", err);
                setError("Failed to load the match generator. Please try reloading.");
            } finally {
                setIsLoadingWasm(false);
            }
        };

        loadWasm();
    }, []);

    function addPlayer(teamIndex: number) {
        const newPlayers = Array.from(players);
        newPlayers[teamIndex].push({ name: '', level: 1, gender: Gender.MALE });
        setPlayers(newPlayers);
    }

    function updatePlayer(teamIndex: number, playerIndex: number, updatedPlayer: Player) {
        const newPlayers = Array.from(players);
        newPlayers[teamIndex][playerIndex] = updatedPlayer;
        setPlayers(newPlayers);
    }

    function addTeam() {
        const newPlayers = Array.from(players);
        newPlayers.push([{ name: '', level: 1, gender: Gender.MALE }]);
        setPlayers(newPlayers);
    }

    function copy() {
        navigator.clipboard.writeText(JSON.stringify(players))
    }

    function paste() {
        const input = window.prompt('json');
        if (input == null) return;
        setPlayers(JSON.parse(input));
    }

    function handleGenerate() {
        if (!wasmModule) {
            console.error("Wasm module not loaded yet.");
            setError("Generator is not ready yet. Please wait or reload.");
            return;
        }
        if (isLoadingWasm) {
            console.log("Wasm module is still loading.");
            return; // Or show feedback
        }

        try {
            setError(null);
            setGenerationResult(null);

            console.log("--- DEBUG: Calling Wasm generateMatches (val version) ---");
            console.log("Value of players (JSON):", JSON.stringify(players, null, 2));
            console.log("Value of courts:", courts);
            console.log("Value of games:", games);
            console.log("-------------------------------------------------------");

            // Call the function bound to generate_matches_val
            // Pass the original JS array directly
            const result = wasmModule.generateMatches(players, courts, games);

            console.log("Result from Wasm:", result);
            setGenerationResult(result);
        } catch (err) {
            console.error("Error calling Wasm function:", err);
            setError(`An error occurred during match generation: ${err}`);
        }
    };

    return (
        <div className={styles.Page}>
            <h1>Auto Match Generator</h1>
            <button className={styles.Control} onClick={copy}>Copy</button>
            <button className={styles.Control} onClick={paste}>Paste</button>
            <div className={styles.TeamsSection}>
                {players.map((team, teamIndex) =>
                    <div className={styles.PlayersSection} key={'PlayersSection' + teamIndex}>
                        {team.map((player, playerIndex) =>
                            <PlayerInput
                                player={player}
                                onPlayerUpdate={(updatedPlayer) => updatePlayer(teamIndex, playerIndex, updatedPlayer)}
                                key={'PlayerInput' + playerIndex}
                            />
                        )}
                        <button onClick={() => addPlayer(teamIndex)}>Add</button>
                    </div>
                )}
                {players.length === 1 && <button onClick={() => addTeam()}>Add Team</button>}
            </div>
            <hr />
            <div className={styles.GameSettings}>
                <label>Number of courts: </label>
                <input
                    className={styles.GameSettingsInput}
                    type='number'
                    value={courts}
                    onChange={(e) => setCourts(Number(e.target.value))} />
                <label>Number of games: </label>
                <input
                    className={styles.GameSettingsInput}
                    type='number'
                    value={games}
                    onChange={(e) => setGames(Number(e.target.value))} />
                <button
                    className={styles.GenerateButton}
                    onClick={handleGenerate}>
                    Generate
                </button>
            </div>
        </div>
    );
}